services:
  - type: web
    name: library-management-system
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/library-management-system-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: -Xmx256m